CREATE TABLE tags (
    id SERIAL PRIMARY KEY,
    user_id BIGINT(16) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL -- ソフトデリート用のカラムを追加
) CHARACTER SET utf8mb4 COLLATE 'utf8mb4_general_ci';