CREATE TABLE task_tags (
    id SERIAL PRIMARY KEY,
    task_id BIGINT(16) NOT NULL,
    tag_id BIGINT(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE 'utf8mb4_general_ci';